package PresentationLayer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class EmailLandlordUnregistered extends JDialog {
    private JPanel contentPane;
    private JButton buttonOK;
    private JButton buttonCancel;
    private JTextArea emailBody;
    private JTextField userEmail;

    EmailLandlordUnregistered() {
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);

        buttonOK.addActionListener(e -> dispose());
        buttonCancel.addActionListener(e -> dispose());

        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                dispose();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(e -> dispose(), KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        contentPane.setPreferredSize(new Dimension(700, 500));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        contentPane.add(toolBar1, BorderLayout.SOUTH);
        buttonOK = new JButton();
        buttonOK.setText("Send");
        toolBar1.add(buttonOK);
        buttonCancel = new JButton();
        buttonCancel.setText("Cancel");
        toolBar1.add(buttonCancel);
        emailBody = new JTextArea();
        contentPane.add(emailBody, BorderLayout.CENTER);
        final JToolBar toolBar2 = new JToolBar();
        toolBar2.setFloatable(false);
        contentPane.add(toolBar2, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("User Email: ");
        toolBar2.add(label1);
        userEmail = new JTextField();
        userEmail.setMinimumSize(new Dimension(200, 30));
        userEmail.setPreferredSize(new Dimension(300, 30));
        toolBar2.add(userEmail);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
