package PresentationLayer;

import javax.swing.*;
import java.awt.*;

public class LandlordGUI implements GUI {
    private JFrame frame;
    private JPanel panel;
    private JButton searchButton;
    private JTextField streetName;
    private JSpinner propertyNumber;
    private JTextField postalCode;
    private JButton registerPropertyButton;
    private JButton showAllButton;
    private JButton logoutButton;

    @Override
    public void updateView() {
        ((SpinnerNumberModel) propertyNumber.getModel()).setMinimum(0);
        frame = new JFrame("ProperTee");
        frame.setContentPane(this.panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    @Override
    public void close() {
        frame.dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        panel.add(toolBar1, BorderLayout.NORTH);
        propertyNumber = new JSpinner();
        toolBar1.add(propertyNumber);
        streetName = new JTextField();
        toolBar1.add(streetName);
        postalCode = new JTextField();
        toolBar1.add(postalCode);
        searchButton = new JButton();
        searchButton.setText("Search");
        toolBar1.add(searchButton);
        final JToolBar toolBar2 = new JToolBar();
        panel.add(toolBar2, BorderLayout.SOUTH);
        registerPropertyButton = new JButton();
        registerPropertyButton.setText("Register Property");
        toolBar2.add(registerPropertyButton);
        showAllButton = new JButton();
        showAllButton.setText("Show All ");
        toolBar2.add(showAllButton);
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        toolBar2.add(logoutButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
