package PresentationLayer;

import Controller.LoginListener;
import Controller.SignupListener;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.Arrays;

public class SignupGUI implements GUI {
    private JFrame frame;
    private JPanel panel;
    private JPasswordField passwordField1;
    private JTextField firstName;
    private JTextField lastName;
    private JTextField email;
    private JTextField username;
    private JButton signupButton;
    private JButton loginButton;
    private JComboBox type;
    private SignupListener listener;

    SignupGUI(SignupListener l) {
        listener = l;
    }

    private String getUserInfo() {
        return (type.getSelectedItem() + "/" + firstName.getText() + "/" + lastName.getText() + "/" + email.getText()
                + "/" + username.getText() + "/" + Arrays.toString(passwordField1.getPassword()));
    }

    private void signup() throws IOException {
        String result = listener.actionPerformed("SIGNUP" + "/" + getUserInfo());

        if (result.equals("null")) {
            JOptionPane.showMessageDialog(new JFrame(), "Signup unsuccessful.");
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Signup successful! Please proceed to login.");
            listener.changeGUI(new LoginGUI(new LoginListener(listener.getClient())));
        }
    }

    private void activateButtons() {
        loginButton.addActionListener(e -> listener.changeGUI(new LoginGUI(new LoginListener(listener.getClient()))));

        signupButton.addActionListener(e -> {
            try {
                signup();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        });
    }

    @Override
    public void updateView() {
        frame = new JFrame("ProperTee");
        frame.setContentPane(this.panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        activateButtons();
    }

    @Override
    public void close() {
        frame.dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panel.setMinimumSize(new Dimension(500, 500));
        panel.setPreferredSize(new Dimension(500, 500));
        firstName = new JTextField();
        firstName.setMaximumSize(new Dimension(500, 30));
        firstName.setMinimumSize(new Dimension(300, 20));
        firstName.setPreferredSize(new Dimension(300, 20));
        firstName.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 10;
        panel.add(firstName, gbc);
        lastName = new JTextField();
        lastName.setMaximumSize(new Dimension(500, 30));
        lastName.setMinimumSize(new Dimension(300, 20));
        lastName.setPreferredSize(new Dimension(300, 20));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 10;
        panel.add(lastName, gbc);
        email = new JTextField();
        email.setMaximumSize(new Dimension(500, 30));
        email.setMinimumSize(new Dimension(300, 20));
        email.setPreferredSize(new Dimension(300, 20));
        email.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 10;
        panel.add(email, gbc);
        username = new JTextField();
        username.setMaximumSize(new Dimension(500, 30));
        username.setMinimumSize(new Dimension(300, 20));
        username.setPreferredSize(new Dimension(300, 20));
        username.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 10;
        panel.add(username, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("First Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Last Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Email");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Username");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label4, gbc);
        passwordField1 = new JPasswordField();
        passwordField1.setMaximumSize(new Dimension(500, 30));
        passwordField1.setMinimumSize(new Dimension(300, 20));
        passwordField1.setPreferredSize(new Dimension(300, 20));
        passwordField1.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 10;
        panel.add(passwordField1, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label5, gbc);
        signupButton = new JButton();
        signupButton.setMaximumSize(new Dimension(10, 30));
        signupButton.setMinimumSize(new Dimension(10, 30));
        signupButton.setPreferredSize(new Dimension(10, 30));
        signupButton.setText("Signup");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(signupButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel.add(spacer2, gbc);
        loginButton = new JButton();
        loginButton.setText("Login");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(loginButton, gbc);
        type = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Renter");
        defaultComboBoxModel1.addElement("Landlord");
        type.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(type, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("User Type");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label6, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel.add(spacer3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
